---
resources:
- name: source
  type: git
  source:
    uri: git@github.com:ecsteam/do-all.git
    branch: master
    private_key: {{github-private-key}}
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:ecsteam/do-all.git
    branch: version
    private_key: {{github-private-key}}
    file: version
    initial_version: 1.0.2
- name: release
  type: github-release
  source:
    user: ecsteam
    repository: do-all
    access_token: {{github-access-token}}
jobs:
- name: bump-minor
  public: true
  plan:
  - get: version
    params: { bump: minor }
  - put: version
    params: { file: version/number }
- name: bump-major
  public: true
  plan:
  - get: version
    params: { bump: major }
  - put: version
    params: { file: version/number }
- name: test-and-build
  plan:
  - get: source
    trigger: true
  - get: version
    params: { bump: patch }
  - task: test
    file: source/ci/tasks/do-test.yml
  - task: build
    file: source/ci/tasks/do-build.yml
  - put: release
    params:
      name: version/number
      tag: version/number
      prefix: v
      globs:
      - build-output/build/*
  - put: version
    params: { file: version/number }
